// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }


// import Link from "next/link";
import dynamic from "next/dynamic";
// import { Inter } from "next/font/google";
import MyHomeImage from "./myTemp/MyHomeImage";
// import "./globals.css";
import "./myGlobal.css";

// const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  const Search4 = dynamic(() => import("../app/SubHead4/SubSearch"));
  const Share = dynamic(() => import("../app/myTemp/Share"));
  return (
    <html lang="en">
      <body>
        {/* <div className="bodyn"> */}
        {/* <h2 className="genAdvert">General advertising</h2>{" "} */}
        <div>{props.GenAdvert}</div>
        <nav>
          {/* {props.pathname} */}
          <MyHomeImage />
          <Search4 />
          <Share />
          {/* <div>{props.share}</div> */}
        </nav>
        <div className="contentDiv">
          <div className="childrenDiv">{props.children}</div>
          {/* <div style={{ backgroundColor: "green", minWidth: "120px" }}>
            {props.rownolegla}
          </div>
          <div style={{ backgroundColor: "pink", minWidth: "120px" }}>
            {props.rownolegla2}
          </div> */}
          <div>{props.ThemAdvert}</div>
        </div>
        {/* <div className="*"> */}
        <footer>
          <p>{metadata.title} </p>
          <p>{metadata.description} </p>
        </footer>
        {/* </div> */}
      </body>
    </html>
  );
}
